### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by dev-kuldeep-singh** [daily-demos/daily-android-demo#23]
After Running the provided application, I got some issues (stack trace provided below), it says "libdaily-android-sdk.so" not found,
I am unable to find such a file in the whole documentation and in this git repo. 
[DailyCoIssue.txt](https://github.com/daily-demos/daily-android-demo/files/13188925/DailyCoIssue.txt)

**Comment by marcus-daily** [comment]
Hi @Kuldeepsp01, thanks for your report. Can I confirm which device architecture you're using please?

I'd expect to see that error when running in the emulator using an x86 image, which we don't support. Our SDK supports x86_64, armeabi-v7a, and arm64-v8a -- I'd recommend using an x86_64 emulator for testing.
